# Generated by Django 5.0.7 on 2024-07-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=255)),
                ("level", models.DecimalField(decimal_places=1, max_digits=2)),
                ("experience", models.IntegerField()),
                ("logo_skill", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="JSONData",
        ),
    ]
