# Generated by Django 5.0.7 on 2024-07-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folio", "0002_skill_delete_jsondata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="logo_skill",
            field=models.ImageField(upload_to=""),
        ),
    ]
