# Generated by Django 5.0.7 on 2024-07-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folio", "0003_alter_skill_logo_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_contact", models.CharField(max_length=255)),
                ("icon_contact", models.ImageField(upload_to="")),
            ],
        ),
    ]
