# Generated by Django 5.0.7 on 2024-07-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folio", "0004_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="link_contact",
            field=models.URLField(blank=True, null=True),
        ),
    ]
