# Generated by Django 5.0.7 on 2024-07-27 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("folio", "0005_contact_link_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="icon_contact",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="link_contact",
            new_name="link",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="text_contact",
            new_name="text",
        ),
    ]
