# Generated by Django 5.0.7 on 2024-07-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folio", "0007_alter_skill_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.CharField(max_length=255)),
                ("link", models.URLField(blank=True, null=True)),
                ("logo", models.ImageField(upload_to="")),
                ("language", models.CharField(max_length=255)),
                ("framework", models.CharField(max_length=255)),
            ],
        ),
    ]
